# Generated by Django 3.1.7 on 2021-03-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_emailedition_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailEdition',
            new_name='Mailing',
        ),
    ]
