# Generated by Django 3.1.7 on 2021-03-19 23:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0004_add_ak_mailer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
