# Generated by Django 3.1.7 on 2021-03-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0004_auto_20210318_2042'),
        ('templates_app', '0005_body_ckeditor'),
    ]

    operations = [
    ]
