# Generated by Django 3.1.7 on 2021-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0006_merge_20210322_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('OWN', 'Owner'), ('TM', 'Team'), ('I', 'Issue'), ('GEN', 'Generic')], default='GEN', max_length=255),
        ),
    ]
