# Generated by Django 3.1.7 on 2021-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0007_tag_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='email_guid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
