# Generated by Django 3.1.7 on 2021-03-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0009_script_tags_sync'),
        ('templates_app', '0008_auto_20210329_1703'),
    ]

    operations = [
    ]
