# Generated by Django 3.1.7 on 2021-04-06 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0010_merge_20210330_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AddField(
            model_name='mailing',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
