# Generated by Django 3.2 on 2021-04-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0012_add_email_creater_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='email_wrapper',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
