# Generated by Django 3.2 on 2021-05-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0014_add_profile_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='preview_text',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='subject',
        ),
        migrations.CreateModel(
            name='MailerSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('preview_text', models.CharField(max_length=255)),
                ('mailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='templates_app.mailing')),
            ],
        ),
    ]