# Generated by Django 3.2.2 on 2021-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0014_add_profile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='tag_ask',
            field=models.ManyToManyField(related_name='email_editions_tag_ask', to='templates_app.Tag'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_camp',
            field=models.ManyToManyField(related_name='email_editions_tag_camp', to='templates_app.Tag'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_dept',
            field=models.ManyToManyField(related_name='email_editions_tag_dept', to='templates_app.Tag'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_ent',
            field=models.ManyToManyField(related_name='email_editions_tag_entity', to='templates_app.Tag'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_i',
            field=models.ManyToManyField(related_name='email_editions_tag_issue', to='templates_app.Tag'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_oth',
            field=models.ManyToManyField(related_name='email_editions_tag_other', to='templates_app.Tag'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_own',
            field=models.ManyToManyField(related_name='email_editions_tag_own', to='templates_app.Tag'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_tgt',
            field=models.ManyToManyField(related_name='email_editions_tag_target', to='templates_app.Tag'),
        ),
    ]
