# Generated by Django 3.2.2 on 2021-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0015_auto_20210516_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='tag_ask',
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_ask',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tag_camp',
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_camp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tag_dept',
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_dept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tag_ent',
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_ent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tag_i',
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_i',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tag_oth',
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_oth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tag_own',
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_own',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tag_tgt',
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_tgt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
