# Generated by Django 3.2 on 2021-05-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0015_mailersubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('preview_text', models.CharField(max_length=255)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='templates_app.mailing')),
            ],
        ),
        migrations.DeleteModel(
            name='MailerSubject',
        ),
    ]
