# Generated by Django 3.2.3 on 2021-05-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0017_auto_20210521_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='tag_ask',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag_camp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag_dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag_ent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag_i',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag_oth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag_own',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag_tgt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
