# Generated by Django 3.2.3 on 2021-05-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0016_renamemailersubject'),
        ('templates_app', '0018_auto_20210521_2117'),
    ]

    operations = [
    ]
