# Generated by Django 3.2 on 2021-07-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0020_addakwrapperid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
