# Generated by Django 3.2.6 on 2021-08-11 18:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0021_mailer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
