# Generated by Django 3.2.6 on 2021-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0022_mailerbody_imagefunc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='tag_help',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
