# Generated by Django 3.2.7 on 2021-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0025_auto_20210921_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsubject',
            name='preview_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
